
name: ala-website

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: SCP Files
      uses: appleboy/scp-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USER }}
        PASSWORD: ${{ secrets.pwd }}
        source: "."
        target: "/var/www/ala.org.br/public_html/ala-website"
